config/routes.rb
Rails.application.routes.draw do
  resources :posts, :departments, :programs, :people, :documents, :universities, only: [:index, :show]

  root 'universities#index'
  get 'documents/:id/download' => 'documents#download', :as => :download

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :university
  belongs_to :head, class_name: "Department"
  has_many :branches, class_name: "Department", foreign_key: "head_id"
  has_many :posts, :as => :placeable
  scope :ordering, -> { (order(:name)) }
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :university
  belongs_to :program
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /application/
  scope :ordering, -> { (order(:fullname)) }

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :subjects
  has_many :posts
  scope :ordering, -> { (order(:lastname)) }

  def to_fullname
    "#{lastname} #{name} #{middlename}"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :person
  belongs_to :placeable, :polymorphic => true
  scope :ordering, -> { (order(:name)) }


  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :university
  has_many :documents
  scope :ordering, -> { (order(:name)) }

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :university
  belongs_to :person
end

app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :parent, class_name: "University"
  has_many :branches, class_name: "University", foreign_key: "parent_id"
  has_many :posts, :as => :placeable
  has_many :university_infos
  has_many :documents
  has_many :programs
  has_attached_file :logo, styles: {medium: "150x150>", thumb: "70x70>"}
  validates_attachment :logo, content_type: {content_type: /\Aimage\/.*\z/}
end

app/models/university_info.rb
class UniversityInfo < ActiveRecord::Base
  belongs_to :university
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :download]

  # GET /documents
  # GET /documents.json
  def index
    if params[:university]
      @documents = Document.where(:university => params[:university]).ordering.includes(:university, :program).page(params[:page])
    else
      @documents = Document.ordering.includes(:university, :program).page(params[:page])
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  def download
    send_file @document.file.path,
    :filename => "#{@document.code}.#{@document.file_ext}",
    :type => @document.file_content_type,
    :disposition => 'attachment'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  def index
    @people = Person.ordering.page(params[:page])
  end

  # GET /people/1
  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts
  def index
    if params[:search]
      @posts = Post.search(params[:search]).ordering.includes(:person, :placeable).page(params[:page])
    else
      @posts = Post.ordering.includes(:person, :placeable).page(params[:page])
    end
    if params[:university]
      if params[:is_manage]
        @posts = @posts.where(:placeable_type => 'University', :placeable_id => params[:university], :is_manage => params[:is_manage])
      else
        @posts = @posts.where(:placeable_type => 'University', :placeable_id => params[:university])
      end
    end
  end

  # GET /posts/1
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  # GET /programs
  # GET /programs.json
  def index
    if params[:university]
      @programs = Program.where(:university => params[:university]).ordering.includes(:university).page(params[:page])
    else
      @programs = Program.ordering.includes(:university).page(params[:page])
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.includes(:university, documents: [:university]).find(params[:id])
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render 'error_messages_for', object: object
  end

  def copyright_years
    start = 2016
    finish = Date.today.year
    "© #{start == finish ? start : "#{start} — #{finish}"}"
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/university_infos_helper.rb
module UniversityInfosHelper
end

app/views/documents/_document.html.haml
=link_to document, class: 'list-group-item' do
  .media
    %b=document.fullname
  .media-body
    %h5.media-heading
      =document.university.name
    %i
      =document.info
  %small.text-muted
    Дата обращения:
    =document.date.strftime("%d.%m.%Y")
  -if document.program_id?
    =document.program.name

app/views/documents/index.html.haml
.page-header
  %h1 Документы
.list-group
  =render @documents
=paginate @documents

app/views/documents/show.html.haml
.page-header
  %h1
    =@document.fullname
  %h3
    %small=@document.info
.row
  .col-md-9
    %dl
      -if @document.university
        %dt=Document.human_attribute_name(:university)
        %dd=link_to @document.university.name,@document.university
      %dt=Document.human_attribute_name(:file)
      %dd= link_to "Скачать (#{number_to_human_size(@document.file_file_size)})", download_path(@document.id)
    -if @document.program
      %h3=Document.human_attribute_name(:program)
      =render @document.program

= link_to 'Назад', documents_path

app/views/people/_person.html.haml
=link_to person, class: 'list-group-item' do
  .media
    %b=person.to_fullname

app/views/people/index.html.haml
.page-header
  %h1 Персоны
.list-group
  =render @people
=paginate @people

app/views/people/show.html.haml
.page-header
  %h1
    =@person.to_fullname
.row
  .col-md-9
    %dl
      -if @person.degree
        %dt=Person.human_attribute_name(:degree)
        %dd=@person.degree
      -if @person.rank
        %dt=Person.human_attribute_name(:rank)
        %dd=@person.rank
      -if @person.beginning_year
        %dt=Person.human_attribute_name(:beginning_year)
        %dd=@person.beginning_year
      -if @person.email
        %dt=Person.human_attribute_name(:email)
        %dd=@person.email
      -if @person.phone
        %dt=Person.human_attribute_name(:phone)
        %dd=@person.phone
      -if @person.upgrade
        %dt=Person.human_attribute_name(:upgrade)
        %dd=@person.upgrade

    -if @person.posts.present?
      %h3=Person.human_attribute_name(:posts)
      =render @person.posts
    -if @person.subjects.present?
      %h3=Person.human_attribute_name(:subjects)
      =render @person.subjects

= link_to 'Назад', people_path

app/views/posts/_post.html.haml
=link_to post, class: 'list-group-item' do

  %b=post.name
  %i
    =post.person.to_fullname

  %h5.media-heading
    =post.placeable.name
  %i
    -if post.placeable_type != 'University'
      =post.placeable.university.name

app/views/posts/index.html.haml
.page-header
  %h1 Должности
.row
  .col-lg-6
    = form_tag(posts_path, :method => "get", class: "bs-component") do
      .form-group
        .input-group
          = text_field_tag :search, params[:search], class: "form-control", placeholder: "Поиск должностей"
          %span.input-group-btn
            = submit_tag 'Search', :name => nil, :class => "btn btn-default"
.list-group
  =render @posts
=paginate @posts

app/views/posts/show.html.haml
.page-header
  %h1
    =@post.name
.row
  .col-md-9
    %dl
      -if @post.placeable_type == 'University'
        %dt=Post.human_attribute_name(:university)
        %dd=link_to @post.placeable.name,@post.placeable
      -else
        %dt=Post.human_attribute_name(:university)
        %dd=link_to @post.placeable.university.name,@post.placeable.university
        %dt=Post.human_attribute_name(:department)
        %dd=link_to @post.placeable.name,@post.placeable
      -if @post.person
        %dt=Post.human_attribute_name(:person)
        %dd=link_to @post.person.to_fullname,@post.person

= link_to 'Назад', posts_path

app/views/programs/_program.html.haml
=link_to program, class: 'list-group-item' do
  .media
    %b=program.name
    %i=program.code
  %small=program.profile
  .media-body
    %h5.media-heading
      =program.university.name
    %i
      -if program.level
        =program.level

app/views/programs/index.html.haml
.page-header
  %h1 Программы
.list-group
  =render @programs

=paginate @programs

app/views/programs/show.html.haml
.page-header
  %h1
    =@program.code
    =@program.name
  %h3
    %small=@program.profile
.row
  .col-md-9
    %dl
      -if @program.university
        %dt=Program.human_attribute_name(:university)
        %dd=link_to "#{@program.university.name}", @program.university
      -if @program.apprent
        %dt=Program.human_attribute_name(:apprent)
        %dd=@program.apprent
      -if @program.form
        %dt=Program.human_attribute_name(:form)
        %dd=@program.form
      -if @program.level
        %dt=Program.human_attribute_name(:level)
        %dd=@program.level
      -if @program.date
        %dt=Program.human_attribute_name(:date)
        %dd=@program.date
      -if @program.documents
        %h3=Program.human_attribute_name(:documents)
        =render @program.documents



= link_to 'Назад', programs_path

app/views/subjects/_subject.html.haml
.list-group-item
  %h4=subject.name
  %small=subject.university.name