config/routes.rb
Rails.application.routes.draw do
  resources :posts, :departments, :programs, :people, :documents, :universities, only: [:index, :show]

  root 'universities#index'
  get 'documents/:id/download' => 'documents#download', :as => :download

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :university
  belongs_to :head, class_name: "Department"
  has_many :branches, class_name: "Department", foreign_key: "head_id"
  has_many :posts, :as => :placeable
  scope :ordering, -> { (order(:name)) }
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :university
  belongs_to :program
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /application/
  scope :ordering, -> { (order(:fullname)) }

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :subjects
  has_many :posts
  scope :ordering, -> { (order(:lastname)) }

  def to_fullname
    "#{lastname} #{name} #{middlename}"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :person
  belongs_to :placeable, :polymorphic => true
  scope :ordering, -> { (order(:name)) }


  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :university
  has_many :documents
  scope :ordering, -> { (order(:name)) }

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :university
  belongs_to :person
end

app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :parent, class_name: "University"
  has_many :branches, class_name: "University", foreign_key: "parent_id"
  has_many :posts, :as => :placeable
  has_many :university_infos
  has_many :documents
  has_many :programs
  has_attached_file :logo, styles: {medium: "150x150>", thumb: "70x70>"}
  validates_attachment :logo, content_type: {content_type: /\Aimage\/.*\z/}
end

app/models/university_info.rb
class UniversityInfo < ActiveRecord::Base
  belongs_to :university
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :download]

  # GET /documents
  # GET /documents.json
  def index
    if params[:university]
      @documents = Document.where(:university => params[:university]).ordering.includes(:university, :program).page(params[:page])
    else
      @documents = Document.ordering.includes(:university, :program).page(params[:page])
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  def download
    send_file @document.file.path,
    :filename => "#{@document.code}.#{@document.file_ext}",
    :type => @document.file_content_type,
    :disposition => 'attachment'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  def index
    @people = Person.ordering.page(params[:page])
  end

  # GET /people/1
  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts
  def index
    if params[:search]
      @posts = Post.search(params[:search]).ordering.includes(:person, :placeable).page(params[:page])
    else
      @posts = Post.ordering.includes(:person, :placeable).page(params[:page])
    end
    if params[:university]
      if params[:is_manage]
        @posts = @posts.where(:placeable_type => 'University', :placeable_id => params[:university], :is_manage => params[:is_manage])
      else
        @posts = @posts.where(:placeable_type => 'University', :placeable_id => params[:university])
      end
    end
  end

  # GET /posts/1
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  # GET /programs
  # GET /programs.json
  def index
    if params[:university]
      @programs = Program.where(:university => params[:university]).ordering.includes(:university).page(params[:page])
    else
      @programs = Program.ordering.includes(:university).page(params[:page])
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.includes(:university, documents: [:university]).find(params[:id])
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.page(params[:page])
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
    @university = University.find(params[:id])
    @university_info = UniversityInfo.where(:university => @university, :version => @university.current_version).first
    @leaders = @university.posts.where(:is_manage => true, :person => Person.where(:version => @university.current_version)).includes(:placeable, :person)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render 'error_messages_for', object: object
  end

  def copyright_years
    start = 2016
    finish = Date.today.year
    "© #{start == finish ? start : "#{start} — #{finish}"}"
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/university_infos_helper.rb
module UniversityInfosHelper
end

app/views/universities/_university.html.haml
=link_to university, class: 'list-group-item' do
  .media
    -if university.logo?
      .media-left=image_tag university.logo.url(:thumb), alt: university.name, class: 'media-object'
    .media-body
      %h4.media-heading
        =university.name

app/views/universities/index.html.haml
.page-header
  %h1 Университеты
.list-group
  =render @universities
=paginate @universities

app/views/universities/show.html.haml
%script{:src => "//api-maps.yandex.ru/2.1/?lang=ru_RU", :type => "text/javascript"}
:javascript
  ymaps.ready(init);
  function init(){
    var myGeocoder = ymaps.geocode(document.getElementById("ymap").getAttribute("data-address"));
    myGeocoder.then(
    function (res) {
        var coord = res.geoObjects.get(0).geometry.getCoordinates()
        myMap = new ymaps.Map("map", {
            center: coord,
            zoom: 15
        });
        myPlacemark = new ymaps.Placemark(coord);
        myMap.geoObjects.add(myPlacemark);
    }
    );
  }
.page-header
  .row
    .col-md-2
      -if @university.logo?
        =image_tag @university.logo.url(:medium), alt: @university.logo, class: 'img-responsive'
    .col-md-10
      %h1#university_name
        =@university.name
      %h3
        %small=@university_info.fullname
.row
  .col-md-6
    %dl
      -if @university_info.regdate
        %dt=UniversityInfo.human_attribute_name(:regdate)
        %dd
          %i.fa.fa-calendar
          =@university_info.regdate
      -if @university_info.address
        %dt=UniversityInfo.human_attribute_name(:address)
        %dd
          %i.fa.fa-map
          =@university_info.address
      -if @university_info.site
        %dt=UniversityInfo.human_attribute_name(:site)
        %dd
          %i.fa.fa-chrome
          =link_to @university_info.site, @university_info.site
      -if @university_info.email
        %dt=UniversityInfo.human_attribute_name(:email)
        %dd
          %i.fa.fa-envelope
          =link_to @university_info.email, "mailto://#{@university_info.email}"
      -if @university_info.telephone
        %dt=UniversityInfo.human_attribute_name(:telephone)
        %dd
          %i.fa.fa-phone.fa-fw
          =link_to @university_info.telephone, "tel:#{@university_info.telephone}"
      -if @university_info.worktime
        %dt=UniversityInfo.human_attribute_name(:worktime)
        %dd=@university_info.worktime


    %dl
      -if @university_info.founder_name
        %dt=UniversityInfo.human_attribute_name(:founder_name)
        %dd=@university_info.founder_name
      -if @university_info.founder_director
        %dt=UniversityInfo.human_attribute_name(:founder_director)
        %dd=@university_info.founder_director
      -if @university_info.founder_address
        %dt=UniversityInfo.human_attribute_name(:founder_address)
        %dd
          %i.fa.fa-map
          =@university_info.founder_address
      -if @university_info.founder_site
        %dt=UniversityInfo.human_attribute_name(:founder_site)
        %dd
          %i.fa.fa-chrome
          =link_to @university_info.founder_site, @university_info.founder_site
      -if @university_info.founder_email
        %dt=UniversityInfo.human_attribute_name(:founder_email)
        %dd
          %i.fa.fa-envelope
          =link_to @university_info.founder_email, "mailto://#{@university_info.founder_email}"
      -if @university_info.founder_phone
        %dt=UniversityInfo.human_attribute_name(:founder_phone)
        %dd
          %i.fa.fa-phone.fa-fw
          =link_to @university_info.founder_phone, "tel:#{@university_info.founder_phone}"

  .col-md-6
    #ymap{data:{address: @university_info.address}}
    #map{:style => "width: 500px; height: 400px"}
.row
  .col-md-9
    %h3=University.human_attribute_name(:leaders)
    =render @leaders
.row
  .col-md-12
    %h3 Ссылки
    =link_to departments_path(:university => @university), class: 'list-group-item' do
      = "Структурные подразделения #{@university.name}"
    =link_to programs_path(:university => @university), class: 'list-group-item' do
      = "Образовательные программы #{@university.name}"
    =link_to documents_path(:university => @university), class: 'list-group-item' do
      = "Документы #{@university.name}"
    =link_to posts_path(:university => @university, :is_manage => false), class: 'list-group-item' do
      = "Преподаватели #{@university.name}"
= link_to 'Назад', universities_path